name: "Setup"
description: "Setup go, go-task"
inputs:
  go-version-file:
    description: "Path to go.mod"
    required: true
  go-task-version:
    description: "Version of go-task"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Setup Go"
      uses: actions/setup-go@v4
      with:
        go-version-file: ${{ inputs.go-version-file }}
    - name: "Install go-task"
      uses: arduino/setup-task@v2
      with:
        version: ${{ inputs.go-task-version }}
