name: "Setup"
description: "Setup go, go-task"
inputs:
  go-version-file:
    description: "Path to go.mod"
    required: true
  install-migrator:
    description: "Install migrator"
    required: false
    default: "false"
  install-linter:
    description: "Install linter"
    required: false
    default: "false"
  token:
    description: "GitHub token"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Setup Go"
      uses: actions/setup-go@v4
      with:
        go-version-file: ${{ inputs.go-version-file }}
    - name: "Install go-task"
      uses: arduino/setup-task@v2
      with:
        version: 3.x
        repo-token: ${{ inputs.token }}
    - name: "Install migrator"
      if: ${{ inputs.install-migrator == 'true' }}
      shell: bash
      run: task install:migrator
    - name: "Install linter"
      if: ${{ inputs.install-linter == 'true' }}
      shell: bash
      run: task install:linter