version: '3'

tasks:
  default:
    desc: List available tasks
    cmds:
      - go-task --list-all

  copy-env:
    desc: Copy default env vars
    cmds:
      - cp .env.sample .env
    silent: false

  up:
    desc: Run docker compose
    cmds:
      - docker compose up 
  
  lint:
    desc: Run local linter config 
    cmds:
      - golangci-lint run 

  lint:remote:
    desc: Run remote linter config 
    cmds:
      - golangci-lint run --config <(curl -sSfL https://raw.githubusercontent.com/fabl3ss/genesis-se-school-linter/refs/heads/main/.golangci.yaml)

  install:
    desc: Install dependencies
    cmds:
      - task: install:linter
      - task: install:migrator

  install:linter:
    desc: Install linter
    cmds:
      - go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest

  install:migrator:
    desc: Install migrator
    cmds:
      - go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

  test:
    desc: Run tests
    cmds:
      - go test ./...