// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.2
// source: proto/weath/v1alpha1/weather.proto

package weatherv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCurrentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentRequest) Reset() {
	*x = GetCurrentRequest{}
	mi := &file_proto_weath_v1alpha1_weather_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentRequest) ProtoMessage() {}

func (x *GetCurrentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_weath_v1alpha1_weather_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentRequest) Descriptor() ([]byte, []int) {
	return file_proto_weath_v1alpha1_weather_proto_rawDescGZIP(), []int{0}
}

func (x *GetCurrentRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type GetCurrentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Temperature   float32                `protobuf:"fixed32,1,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Humidity      float32                `protobuf:"fixed32,2,opt,name=humidity,proto3" json:"humidity,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentResponse) Reset() {
	*x = GetCurrentResponse{}
	mi := &file_proto_weath_v1alpha1_weather_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentResponse) ProtoMessage() {}

func (x *GetCurrentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_weath_v1alpha1_weather_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentResponse) Descriptor() ([]byte, []int) {
	return file_proto_weath_v1alpha1_weather_proto_rawDescGZIP(), []int{1}
}

func (x *GetCurrentResponse) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *GetCurrentResponse) GetHumidity() float32 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

func (x *GetCurrentResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_proto_weath_v1alpha1_weather_proto protoreflect.FileDescriptor

const file_proto_weath_v1alpha1_weather_proto_rawDesc = "" +
	"\n" +
	"\"proto/weath/v1alpha1/weather.proto\x12\x10weather.v1alpha1\"'\n" +
	"\x11GetCurrentRequest\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\"t\n" +
	"\x12GetCurrentResponse\x12 \n" +
	"\vtemperature\x18\x01 \x01(\x02R\vtemperature\x12\x1a\n" +
	"\bhumidity\x18\x02 \x01(\x02R\bhumidity\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription2i\n" +
	"\x0eWeatherService\x12W\n" +
	"\n" +
	"GetCurrent\x12#.weather.v1alpha1.GetCurrentRequest\x1a$.weather.v1alpha1.GetCurrentResponseBtZrgithub.com/GenesisEducationKyiv/software-engineering-school-5-0-velosypedno/proto/weather/v1alpha1;weatherv1alpha1b\x06proto3"

var (
	file_proto_weath_v1alpha1_weather_proto_rawDescOnce sync.Once
	file_proto_weath_v1alpha1_weather_proto_rawDescData []byte
)

func file_proto_weath_v1alpha1_weather_proto_rawDescGZIP() []byte {
	file_proto_weath_v1alpha1_weather_proto_rawDescOnce.Do(func() {
		file_proto_weath_v1alpha1_weather_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_weath_v1alpha1_weather_proto_rawDesc), len(file_proto_weath_v1alpha1_weather_proto_rawDesc)))
	})
	return file_proto_weath_v1alpha1_weather_proto_rawDescData
}

var file_proto_weath_v1alpha1_weather_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_weath_v1alpha1_weather_proto_goTypes = []any{
	(*GetCurrentRequest)(nil),  // 0: weather.v1alpha1.GetCurrentRequest
	(*GetCurrentResponse)(nil), // 1: weather.v1alpha1.GetCurrentResponse
}
var file_proto_weath_v1alpha1_weather_proto_depIdxs = []int32{
	0, // 0: weather.v1alpha1.WeatherService.GetCurrent:input_type -> weather.v1alpha1.GetCurrentRequest
	1, // 1: weather.v1alpha1.WeatherService.GetCurrent:output_type -> weather.v1alpha1.GetCurrentResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_weath_v1alpha1_weather_proto_init() }
func file_proto_weath_v1alpha1_weather_proto_init() {
	if File_proto_weath_v1alpha1_weather_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_weath_v1alpha1_weather_proto_rawDesc), len(file_proto_weath_v1alpha1_weather_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_weath_v1alpha1_weather_proto_goTypes,
		DependencyIndexes: file_proto_weath_v1alpha1_weather_proto_depIdxs,
		MessageInfos:      file_proto_weath_v1alpha1_weather_proto_msgTypes,
	}.Build()
	File_proto_weath_v1alpha1_weather_proto = out.File
	file_proto_weath_v1alpha1_weather_proto_goTypes = nil
	file_proto_weath_v1alpha1_weather_proto_depIdxs = nil
}
