version: '3.8'

services:
  test-redis:
    image: redis:alpine
    ports:
      - "6381:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "ping"]
      interval: 2s
      timeout: 2s
      retries: 4

  test-waiter:
    image: alpine
    depends_on:
      test-redis:
        condition: service_healthy

