// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.2
// source: proto/sub/v1alpha2/sub.proto

package subv1alpha2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Frequency     string                 `protobuf:"bytes,2,opt,name=frequency,proto3" json:"frequency,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_proto_sub_v1alpha2_sub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sub_v1alpha2_sub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_sub_v1alpha2_sub_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SubscribeRequest) GetFrequency() string {
	if x != nil {
		return x.Frequency
	}
	return ""
}

func (x *SubscribeRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type SubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_proto_sub_v1alpha2_sub_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sub_v1alpha2_sub_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_proto_sub_v1alpha2_sub_proto_rawDescGZIP(), []int{1}
}

func (x *SubscribeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ConfirmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmRequest) Reset() {
	*x = ConfirmRequest{}
	mi := &file_proto_sub_v1alpha2_sub_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmRequest) ProtoMessage() {}

func (x *ConfirmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sub_v1alpha2_sub_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmRequest.ProtoReflect.Descriptor instead.
func (*ConfirmRequest) Descriptor() ([]byte, []int) {
	return file_proto_sub_v1alpha2_sub_proto_rawDescGZIP(), []int{2}
}

func (x *ConfirmRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ConfirmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmResponse) Reset() {
	*x = ConfirmResponse{}
	mi := &file_proto_sub_v1alpha2_sub_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmResponse) ProtoMessage() {}

func (x *ConfirmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sub_v1alpha2_sub_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmResponse.ProtoReflect.Descriptor instead.
func (*ConfirmResponse) Descriptor() ([]byte, []int) {
	return file_proto_sub_v1alpha2_sub_proto_rawDescGZIP(), []int{3}
}

func (x *ConfirmResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UnsubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeRequest) Reset() {
	*x = UnsubscribeRequest{}
	mi := &file_proto_sub_v1alpha2_sub_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeRequest) ProtoMessage() {}

func (x *UnsubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sub_v1alpha2_sub_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeRequest.ProtoReflect.Descriptor instead.
func (*UnsubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_sub_v1alpha2_sub_proto_rawDescGZIP(), []int{4}
}

func (x *UnsubscribeRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type UnsubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeResponse) Reset() {
	*x = UnsubscribeResponse{}
	mi := &file_proto_sub_v1alpha2_sub_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeResponse) ProtoMessage() {}

func (x *UnsubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sub_v1alpha2_sub_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeResponse.ProtoReflect.Descriptor instead.
func (*UnsubscribeResponse) Descriptor() ([]byte, []int) {
	return file_proto_sub_v1alpha2_sub_proto_rawDescGZIP(), []int{5}
}

func (x *UnsubscribeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_sub_v1alpha2_sub_proto protoreflect.FileDescriptor

const file_proto_sub_v1alpha2_sub_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/sub/v1alpha2/sub.proto\x12\fsub.v1alpha2\"Z\n" +
	"\x10SubscribeRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1c\n" +
	"\tfrequency\x18\x02 \x01(\tR\tfrequency\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\"-\n" +
	"\x11SubscribeResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"&\n" +
	"\x0eConfirmRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"+\n" +
	"\x0fConfirmResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"*\n" +
	"\x12UnsubscribeRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"/\n" +
	"\x13UnsubscribeResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xff\x01\n" +
	"\x13SubscriptionService\x12L\n" +
	"\tSubscribe\x12\x1e.sub.v1alpha2.SubscribeRequest\x1a\x1f.sub.v1alpha2.SubscribeResponse\x12F\n" +
	"\aConfirm\x12\x1c.sub.v1alpha2.ConfirmRequest\x1a\x1d.sub.v1alpha2.ConfirmResponse\x12R\n" +
	"\vUnsubscribe\x12 .sub.v1alpha2.UnsubscribeRequest\x1a!.sub.v1alpha2.UnsubscribeResponseBlZjgithub.com/GenesisEducationKyiv/software-engineering-school-5-0-velosypedno/proto/sub/v1alpha2;subv1alpha2b\x06proto3"

var (
	file_proto_sub_v1alpha2_sub_proto_rawDescOnce sync.Once
	file_proto_sub_v1alpha2_sub_proto_rawDescData []byte
)

func file_proto_sub_v1alpha2_sub_proto_rawDescGZIP() []byte {
	file_proto_sub_v1alpha2_sub_proto_rawDescOnce.Do(func() {
		file_proto_sub_v1alpha2_sub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sub_v1alpha2_sub_proto_rawDesc), len(file_proto_sub_v1alpha2_sub_proto_rawDesc)))
	})
	return file_proto_sub_v1alpha2_sub_proto_rawDescData
}

var file_proto_sub_v1alpha2_sub_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_sub_v1alpha2_sub_proto_goTypes = []any{
	(*SubscribeRequest)(nil),    // 0: sub.v1alpha2.SubscribeRequest
	(*SubscribeResponse)(nil),   // 1: sub.v1alpha2.SubscribeResponse
	(*ConfirmRequest)(nil),      // 2: sub.v1alpha2.ConfirmRequest
	(*ConfirmResponse)(nil),     // 3: sub.v1alpha2.ConfirmResponse
	(*UnsubscribeRequest)(nil),  // 4: sub.v1alpha2.UnsubscribeRequest
	(*UnsubscribeResponse)(nil), // 5: sub.v1alpha2.UnsubscribeResponse
}
var file_proto_sub_v1alpha2_sub_proto_depIdxs = []int32{
	0, // 0: sub.v1alpha2.SubscriptionService.Subscribe:input_type -> sub.v1alpha2.SubscribeRequest
	2, // 1: sub.v1alpha2.SubscriptionService.Confirm:input_type -> sub.v1alpha2.ConfirmRequest
	4, // 2: sub.v1alpha2.SubscriptionService.Unsubscribe:input_type -> sub.v1alpha2.UnsubscribeRequest
	1, // 3: sub.v1alpha2.SubscriptionService.Subscribe:output_type -> sub.v1alpha2.SubscribeResponse
	3, // 4: sub.v1alpha2.SubscriptionService.Confirm:output_type -> sub.v1alpha2.ConfirmResponse
	5, // 5: sub.v1alpha2.SubscriptionService.Unsubscribe:output_type -> sub.v1alpha2.UnsubscribeResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_sub_v1alpha2_sub_proto_init() }
func file_proto_sub_v1alpha2_sub_proto_init() {
	if File_proto_sub_v1alpha2_sub_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sub_v1alpha2_sub_proto_rawDesc), len(file_proto_sub_v1alpha2_sub_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sub_v1alpha2_sub_proto_goTypes,
		DependencyIndexes: file_proto_sub_v1alpha2_sub_proto_depIdxs,
		MessageInfos:      file_proto_sub_v1alpha2_sub_proto_msgTypes,
	}.Build()
	File_proto_sub_v1alpha2_sub_proto = out.File
	file_proto_sub_v1alpha2_sub_proto_goTypes = nil
	file_proto_sub_v1alpha2_sub_proto_depIdxs = nil
}
