version: '3'

tasks:
  default:
    desc: List available tasks
    cmds:
      - go-task --list-all

  lint:
    desc: Run local linter config 
    cmds:
      - golangci-lint run

  copy:env:
    desc: Copy default env vars
    cmds:
      - cp .env.sample .env
    silent: false

  copy:env:optional:
     desc: Ensure .env exists
     cmds:
      - |
        if [ ! -f .env ]; then
          echo ".env not found, copying from .env.sample"
          cp .env.sample .env
        else
          echo ".env already exists"
        fi

  run:debug:
    desc: Run API in debug mode
    dotenv: [".env"]
    cmds:
      - go run cmd/main.go
    env:
      GRPC_HOST: localhost
      DB_HOST: localhost
      LOG_DIR: ./logs

  test:
    desc: Run all tests
    cmds:
      - task: test:unit
      - task: test:integration
  
  test:unit:
    desc: Run unit tests
    cmds:
      - go test ./... -v -tags=unit

  test:integration:
    desc: Run integration tests
    dotenv: [".env.sample"]
    env:
      WEATHER_SERVICE_PORT: 50104
      WEATHER_SERVICE_HOST: localhost
      GRPC_PORT: 50103
      GRPC_HOST: localhost
      DB_PORT: 5433
      RABBITMQ_PORT: 5673
      DB_HOST: localhost
      LOG_DIR: ./logs
      HTTP_PORT: 8093
    cmds:
      - task: copy:env:optional
      - docker compose -f docker-compose.test.yml up -d
      - defer: docker compose -f docker-compose.test.yml down
      - migrate -database "${DB_DRIVER}://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable" -path db/migrations up
      - go test ./... -v -tags=integration

  install:
    desc: Install dependencies
    cmds:
      - task: install:linter

  install:linter:
    desc: Install linter
    cmds:
      - go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.1.6

  install:migrator:
    desc: Install migrator
    cmds:
      - go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@v4.16.2

  migrate:up:
    desc: Run migrations
    cmds:
      - migrate -database "${DB_DRIVER}://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable" -path db/migrations up