name: GO

on: push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install go and go-task
      uses: ./.github/actions/setup
      with:
        go-version-file: './go.mod'
        install-linter: 'true'

    - name: Run linter
      run: task lint
  
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install go and go-task
      uses: ./.github/actions/setup
      with:
        go-version-file: './go.mod'
    
    - name: Run tests
      run: task test

  migrations:
    name: Migrations
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres_pass
          POSTGRES_DB: weather
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install go and go-task
      uses: ./.github/actions/setup
      with:
        go-version-file: './go.mod'
        install-migrator: 'true'

    - name: Wait for postgres
      run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            sleep 1
          done

    - name: Run migrations
      run: migrate -database "postgres://postgres:postgres_pass@localhost:5432/weather?sslmode=disable" -path db/migrations up

          