name: Gateway

on: push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install go and go-task
      uses: ./.github/actions/setup
      with:
        go-version-file: './go.mod'
        install-linter: 'true'
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run linter
      run: cd gateway && task lint
  
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install go and go-task
      uses: ./.github/actions/setup
      with:
        go-version-file: './go.mod'
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Run tests
      run: cd gateway && task test:unit